// Autogenerated by codegen.lua during premake process

#pragma once

namespace Samples
{
    namespace _1d
    {
        namespace Regular
        {
            inline void AutoTest(void)
            {
                // Regular
                {
                    std::vector<float> samples;
                    Regular(samples, 16);
                }
                // RegularCentered
                {
                    std::vector<float> samples;
                    RegularCentered(samples, 16);
                }
                // RegularCenteredOffset
                {
                    std::vector<float> samples;
                    RegularCenteredOffset(samples, 16);
                }
            }
        };
    };
};
