// Autogenerated by codegen.lua during premake process

#pragma once

#include <vector>

namespace Samples
{
    namespace _1d
    {
        namespace Regular
        {
            void Regular(std::vector<float>& values, size_t numValues);
            void RegularCentered(std::vector<float>& values, size_t numValues);
            void RegularCenteredOffset(std::vector<float>& values, size_t numValues);
        };
    };
};
