function scandir(command)
    local i, t, popen = 0, {}, io.popen
    local pfile = popen(command)
    for filename in pfile:lines() do
        i = i + 1
        t[i] = filename
    end
    pfile:close()
    return t
end

print "=====Generating Code====="

local file = io.open("./src/samples/samples.h", "w")
file:write("// Autogenerated by codegen.lua during premake process\n\n#pragma once\n\n")
local sampleTypes = scandir('cd ./src/samples/ && ls -d ./*/ && cd ../..')
for k,v in pairs(sampleTypes) do
	local sampleType = string.sub(v,3,-2)
	file:write('#include "'..sampleType..'/'..sampleType..'.h"\n')
end
file:close()


print "========================="