// Autogenerated by codegen.lua during premake process

#pragma once

#include <vector>

namespace Samples
{
    namespace _1d
    {
        namespace IrrationalNumbers
        {
            void GoldenRatio(std::vector<float>& values, size_t numValues);
            void Pi(std::vector<float>& values, size_t numValues);
            void Sqrt2(std::vector<float>& values, size_t numValues);
        };
    };
};
