// Autogenerated by codegen.lua during premake process

#pragma once

namespace Samples
{
    namespace _1d
    {
        namespace LDS
        {
            inline void AutoTest(void)
            {
                // Sobol
                {
                    std::vector<float> samples;
                    Sobol(samples, 16);
                    FILE* file = fopen("output/samples/_1d/LDS/Sobol.txt", "w+b");
                    fprintf(file, "Sobol %zu samples\r\n  Discrepancy: %0f\r\n  Wrap: %0f\r\n\r\n",
                        samples.size(),
                        Tests::_1d::Discrepancy::CalculateDiscrepancy(samples),
                        Tests::_1d::Discrepancy::CalculateDiscrepancyWrapAround(samples)
                    );
                    fclose(file);
                    Tests::_1d::Numberline::MakeNumberline("output/samples/_1d/LDS/Sobol.png", samples, 512);
                }
            }
        };
    };
};
