// Autogenerated by codegen.lua during premake process

#pragma once

#include <vector>

namespace Samples
{
    namespace _1d
    {
        namespace LDS
        {
            void Sobol(std::vector<float>& values, size_t numValues);
        };
    };
};
