// Autogenerated by codegen.lua during premake process

#pragma once

namespace Samples
{
    namespace _1d
    {
        namespace UniformRandom
        {
            inline void AutoTest(void)
            {
                // UniformRandom
                {
                    std::vector<float> samples;
                    Samples::_1d::UniformRandom::UniformRandom(samples, 16);
                }
            }
        };
    };
};
